### ISSUE TITLE
[Create Annotation] drug highlight incorrectly added in DDI form

### ISSUE THREAD

**Issue by ningyifan** [dbmi-pitt/dbmi-annotator#12]
Drug highlight annotation isn't completely add to drug lists in DDI from. 
The wrong cases could be 
(1) single highlight split to couple of string. (ex. mirtazapine is added to drug list as "m" and "irtazapine")

(2) incorrect number of occurrences. (ex. mirtazapine appear in DDI quote once but there are two more mirtazapine added to drugs list in DDI form)

(3) drug lists in DDI form added some string that not been annotated as drug mention. (ex. "ae" is not in sentence A but added into form as a drug selection)

**Comment by Louisa78909** [comment]
For most of the drug name, the user can highlight by double clicking. But if the drug name contains "-", then they have to paste it first and highlight it. It will be nice if we can use the say way to highlight the drug name and be consistent.
