### ISSUE TITLE
Importing other's work

### ISSUE THREAD

**Issue by bas172** [dbmi-pitt/dbmi-annotator#164]
After you "Import" others' work, the window does not automatically close.  For a while, it seemed as if nothing was happening and took a while to realize everything was loaded.  If the window could automatically close, it would be helpful. Also it may be beneficial to make it clear you have to check an invisible box next to the annotation set in order to load the work.

**Comment by ningyifan** [comment]
Very helpful issue! The invisible box is the browser issue which supposed to present as checkbox. Failed close window when clicked import is a bug that I am fixing now.
