### ISSUE TITLE
[Load Annotations]The number of annotations was not correct on the main page.

### ISSUE THREAD

**Issue by Louisa78909** [dbmi-pitt/dbmi-annotator#20]
The numbers of annotations that user did was not correct on the main page. The database has the correct information, but was not loaded to the main page correctly.

**Comment by ningyifan** [comment]
This is the same as issue #11

**Comment by ningyifan** [comment]
Show numbers of DDI annotation rather than both drug mention and DDI.   Limitation: only supports total numbers of annotation less than 20 at this point.

**Comment by ningyifan** [comment]
allowing 120 DDI counts right now. annotator store only supports maximum results 200
