### ISSUE TITLE
Export file format (not currently CSV)

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/dbmi-annotator#204]
The export file format is described as "CSV" ("comma separated values") but the file I've downloaded from the test account on the test instance doesn't appear to comply. For instance, there are no commas between fields. It may worth be worth noting that the " symbol is used as a text qualifier.

**Comment by rkboyce** [comment]
Ok. We will change to 'tsv' so that it is clear that tab is the delimiter
