### ISSUE TITLE
Why "refutes" and not "challenges" for the Ev relationship?

### ISSUE THREAD

**Issue by jodischneider** [dbmi-pitt/dbmi-annotator#206]
Why "refutes" and not "challenges" for the Ev relationship? ("Refute" suggests that the evidence is conclusive; its counterpart "supports" does not.)

**Comment by rkboyce** [comment]
Good suggestion - will do.

**Comment by ningyifan** [comment]
We will change the label of evidence relationship to "challenges" and still save as refutes back-end at this point.
