### ISSUE TITLE
Please add intramuscular to the formulation drop down for drug dosage

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/dbmi-annotator#209]
An example of where this is needed is for Olanzapine interact with Lorazepam in the olanzapine label where doses should be IM but are currently listed as IV

**Comment by ningyifan** [comment]
Are we going to change all "IV" to "IM"? If it does, we may need to update the option in existing data. The safe way to achieve that is keep the "IV" and then add "IM". Please advise.
