### ISSUE TITLE
obstructing sentence span making it hard create multiple annotations

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/dbmi-annotator#30]
The annotation review/summary pop up tends to obstruct sentence spans making it hard create multiple annotations on the same sentence span:

![wv2](https://cloud.githubusercontent.com/assets/104793/13127825/97c3e972-d59f-11e5-99ed-eebbb7389e71.png)

The user might try to use the "x" in the upper right corner to dismiss the popup and accidentally delete a prior annotation (or multiple annotations?)

**Comment by ningyifan** [comment]
It's the problem of how to organize multiple viewers (the pop up summary) with text. Originally, it's horizontally display fields in one viewer so that we will have multiple viewers vertically. I will put this issue in high priority.
