### ISSUE TITLE
Dealing with multiple annotations in the same span

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/dbmi-annotator#31]
Hi,

I am attaching two documents that Katrina prepared to help the annotator become more user friendly for cases where there is allot of information in a single sentence span. Please see attached.
[PDDIannotationinterfacechanges.pdf](https://github.com/dbmi-pitt/dbmi-annotator/files/135306/PDDIannotationinterfacechanges.pdf)
[DDIinterface.docx](https://github.com/dbmi-pitt/dbmi-annotator/files/135307/DDIinterface.docx)

**Comment by ningyifan** [comment]
Thanks for your documents. I added them to our repo at "https://github.com/dbmi-pitt/dbmi-annotator/tree/master/design/ui-katrina-02182016". I will improve the UI components based on katrina's idea.
