### ISSUE TITLE
pop up drug annotator label

### ISSUE THREAD

**Issue by bas172** [dbmi-pitt/dbmi-annotator#37]
After a drug is highlighted, a box stating who the annotator is pops up whenever the cursor is over the word and follows the cursor as you move it.  Similar to the problem previously discussed about how the drug label statements move with the cursor and obstruct the readers view, maybe this box could only appear if you click on the specific drug or combine it with the actual drug label statement.

**Comment by ningyifan** [comment]
On current version, I modified the way of trigger the pop up box from mouse over to click. I will upgrade the public facing version by end of this week.
